### ISSUE TITLE
Common Data Serviceと訳されているがCommon Data Modelの間違いでは

### ISSUE THREAD

**Issue by kazy101644** [MicrosoftDocs/powerbi-docs.ja-jp#13]
データは、Azure Data Lake Storage Gen2 の Common Data Service 内にエンティティとして保存されます。 データフローの作成と管理は、Power BI サービスのアプリ ワークスペースで行います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1d4e74b8-9f4a-a195-7347-cf6732ffeab5
* Version Independent ID: a1513d50-f098-9b75-2b48-94e08ee34751
* Content: [Power BI でのデータフローについて学習する - Power BI](https://docs.microsoft.com/ja-jp/power-bi/service-dataflows-overview#feedback)
* Content Source: [powerbi-docs/service-dataflows-overview.md](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/blob/live/powerbi-docs/service-dataflows-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
こんにちは、@kazy101644

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@kazy101644

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/power-bi/service-dataflows-overview#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
