### ISSUE TITLE
The Japanese translation of the image description is incorrect! !

### ISSUE THREAD

**Issue by github129** [MicrosoftDocs/powerbi-docs.ja-jp#21]
[フィードバックをこちらに入力してください]
English
https://docs.microsoft.com/en-us/power-bi/service-dataflows-overview
![image](https://user-images.githubusercontent.com/25972825/69525064-a8425d80-0faa-11ea-9694-f9ff536b4906.png)

Japanese
https://docs.microsoft.com/ja-jp/power-bi/service-dataflows-overview
![image](https://user-images.githubusercontent.com/25972825/69525126-c740ef80-0faa-11ea-94b0-1325bfe13435.png)

Look at the red line.
ADLS Gen2 does not include Common Data Service. The correct one is Common Data Model.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1d4e74b8-9f4a-a195-7347-cf6732ffeab5
* Version Independent ID: a1513d50-f098-9b75-2b48-94e08ee34751
* Content: [Power BI でのデータフローについて学習する - Power BI](https://docs.microsoft.com/ja-jp/power-bi/service-dataflows-overview)
* Content Source: [powerbi-docs/service-dataflows-overview.md](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/blob/live/powerbi-docs/service-dataflows-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @github129
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @github129
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/power-bi/service-dataflows-overview

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
