### ISSUE TITLE
English strings remain in Japanese page

### ISSUE THREAD

**Issue by nokura** [MicrosoftDocs/powerbi-docs.ja-jp#5]
I see the following strings are in English while other strings are translated.
Items within a Premium capacity

Accessing app workspaces (as members or admins) and publishing apps requires a Power BI Pro license.

Sharing an app requires a Pro license, but consuming an app doesn't.

All dashboard recipients, regardless of the license they're assigned, can set data alerts.

REST APIs for embedding use a service account with a Pro license, rather than a user account.

My workspace in Shared capacity

Sharing and consuming an app both require a Pro license.
App workspaces in Shared capacity

Any app usage requires a Pro license.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 830ea9dd-618c-897e-4cce-97edc93df585
* Version Independent ID: 135f4574-36ed-6a3b-85d4-a565c57a1312
* Content: [Microsoft Power BI Premium とは何ですか? - Power BI](https://docs.microsoft.com/ja-jp/power-bi/service-premium)
* Content Source: [powerbi-docs/service-premium.md](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/blob/live/powerbi-docs/service-premium.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by CeciAc** [comment]
Hello, @nokura 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @nokura
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/power-bi/service-premium.  (and all locales with the same issue)

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
