### ISSUE TITLE
Bigqueryの請求先プロジェクトのオプション設定方法について

### ISSUE THREAD

**Issue by naoyamuto** [MicrosoftDocs/powerbi-docs.ja-jp#7]
* Power BIとbigqueryの連携を検討しています。
* 記事の中に以下の記述があるのですが、具体的にこのオプションをどこで指定すればよいかわかりません。すみませんが、設定方法について教えていただけないでしょうか？

## 記述内容

ソースの手順の基になる M で次のオプションを指定します。これは、Power BI Desktop で Power Query エディターを使用してカスタマイズできます。
```
Source = GoogleBigQuery.Database([BillingProject="Include-Billing-Project-Id-Here"])
```

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 974455fc-88ff-6a48-4dd0-036419eaa849
* Version Independent ID: 2700a36d-177a-7596-2d91-4f0fc9f9d695
* Content: [Power BI Desktop で Google BigQuery データベースに接続する - Power BI](https://docs.microsoft.com/ja-jp/power-bi/desktop-connect-bigquery)
* Content Source: [powerbi-docs/desktop-connect-bigquery.md](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/blob/live/powerbi-docs/desktop-connect-bigquery.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
こんにちは、@naoyamuto
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
